version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      # These two tests should run in parallel. Make it so!
      - run:
          name: Run Hello test
          command: |
            bash ./project/04\ Parallelism/src/test_hello.sh
      - run:
          name: Run Goodbye test
          command: |
            bash ./project/04\ Parallelism/src/test_goodbye.sh
workflows:
  test-workflow:
    jobs:
      - test